# Generated by Django 4.2.8 on 2024-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('hinh_anh', models.ImageField(upload_to='images/dich_vu/')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GioiThieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('hinh_anh', models.ImageField(upload_to='images/gioi_thieu/')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('dia_chi', models.CharField(max_length=500)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('noi_dung', models.TextField()),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hinh_anh', models.ImageField(upload_to='images/san_pham/')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('hinh_anh', models.ImageField(upload_to='images/tin_tuc/')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrangChu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('hinh_anh', models.ImageField(upload_to='images/trang_chu/')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
